newIssueWelcomeComment: >
  Hello there!👋 Elevate heartly welcomes you to the project!💖
  
  <img src="https://media.giphy.com/media/vFKqnCdLPNOKc/giphy.gif" width="60" height="60" />
  
  Thank you and congrats🎉for opening your very first issue in this project.Hope you have a great time there!😄 
  
  You may submit a PR if you like! If you want to report a bug🐞 
  please follow our [Issue Template](https://github.com/Elevate-Lab/Import-Template/tree/main/.github/ISSUE_TEMPLATE). 
  Also make sure you include steps to reproduce it and be patient while we get back to you.😄

newPRWelcomeComment: >
  Hello there!👋 Welcome to the project!💖
  
  Thank you and congrats🎉 for opening your first pull request.✨.We will get back to you as soon as we can.😄

firstPRMergeComment: >
  Congrats on merging your first pull request! 🎉🎉🎉
